# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sruser
          POSTGRES_PASSWORD: sruser
          POSTGRES_DB: service_reports
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm i
        working-directory: api
      - run: npm run build --if-present
        working-directory: api
      - run: npm run lint
        working-directory: api
      - name: Connect to PostgreSQL
        run: npm run test-git
        working-directory: api
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
